### ISSUE TITLE
[BUG] Bug in sample aad-resource-server configuration yml

### ISSUE THREAD

**Issue by tommyNy** [Azure-Samples/azure-spring-boot-samples#616]
On this page 

https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.5.0/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server

param app-id-uri is localized on bad level:

is
```yaml
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_CLIENT_ID}
          app-id-uri: ${APP_ID_URI}
```
should be
```yaml
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_CLIENT_ID}
        app-id-uri: ${APP_ID_URI}
```
